# This is a basic workflow to help you get started with Actions

name: Deploy Dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for non master branch
  push:
    branches-ignore: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: setup-node
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'npm'
    - name: install-dependencies
      run: npm install
    - name: Run ESLint
      run: npx eslint . --ext .js,.jsx,.ts,.tsx
  deploy:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: deploy ppukj nodejs bot
        uses: appleboy/ssh-action@v0.1.4 #SSH to VPS
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.SSH_USERNAME}}
          password: ${{secrets.SSH_PASSWORD}}
          
          script: | #Script to run after SSH-ing
            cd bots/Music-bot/
            git fetch --all
            git stash
            git checkout ${{ steps.extract_branch.outputs.branch }}
            git pull origin ${{ steps.extract_branch.outputs.branch }}
            npm install
            pm2 stop ppukj-music-bot-dev
            pm2 start "npm run dev" --name ppukj-music-bot-dev
            echo 'ppukj-music-bot-dev has been deployed!'
